### ISSUE TITLE
Upgrade EDG to Geoportal server 1.2.8

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#26]
Was released July 7:  https://github.com/Esri/geoportal-server/wiki
Contains bugfixes and improvements, particularly FGDC status checker fix.

**Comment by torrin47** [comment]
Deployed gpt-1.2.8,jar, seems to be working, but shouldn't there also be a bunch of other files to merge? I'm seeing a number of changes under this directory structure:
https://github.com/Esri/geoportal-server/tree/master/geoportal/www
that I guess must be JSP updates (and other HTML elements?), including fixes for a number of issues we raised. Is this still in the pipeline, or could we have a look at merging this with our code?

**Comment by Saisuma004** [comment]
I will be adding those changes.

**Comment by torrin47** [comment]
Moving status checker to separate ticket #33 otherwise everything is working!
