### ISSUE TITLE
Add in-line guidance to non-geo editor template

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#36]
It would be very user friendly if the non-geo editor form could contain panes that are hidden initially but can be expanded to show help from the EPA Metadata Technical Specification and styleguide. Because this editor template might be reused and/or embedded in different contexts, it would be great if the text for this help could be stored in a JSON file hosted on the EDG file and retrieved on pageload and inserted into the correct place on the page dynamically. That way, if we need to update the guidance, we just update the JSON file, and all of the implementations receive the update.

**Comment by aergul** [comment]
This can work well so long as guidance content uses minimal HTML and makes no assumptions of display device.

**Comment by jzichichi** [comment]
@aergul - this appears to work well; I suppose I will move this item to done and test the remaining elements when the file referenced in item #65  is updated.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#35
