### ISSUE TITLE
All non-geo metadata elements

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#59]
For reference, please see the EPA Metadata Technical Specification:
https://www.epa.gov/geospatial/epa-metadata-technical-specification
and the non-geo spreadsheet (contains valid value domains)[https://app.zenhub.com/files/98460260/3ad4e01d-b2f8-42ef-bf9d-f0932d4e75e2/download](https://app.zenhub.com/files/98460260/3ad4e01d-b2f8-42ef-bf9d-f0932d4e75e2/download)

General Principles:

- The editor will be a simple, clean, modern, single-page website, hosted on the EDG server and accessible to the public. No login will be required to edit and submit an extramural record.
- There will be a clear visual distinction between mandatory and optional elements.
- Dropdown menus or multiselects with choices matching the EPA Metadata Technical Specification will be available for all elements with clearly defined domains.
-  The page will contain built-in validation, both for syntax (valid email addresses and URLs) as well as logic (restricted data must have valid CUI justifications).
-  Guidance will be available in the page for each element – not necessarily visible at first, but accessible without navigating away from the page. The content for this guidance should be loaded from a separate JSON file, so that the EDG team can maintain and update a single file of guidance that can be loaded into multiple editors.

**Comment by torrin47** [comment]
Going to break the elements into smaller groups.  Keep this ticket for reference.

**Comment by jzichichi** [comment]
@torrin47 - would it make sense to move this item to the icebox or something else less "active" than the review column?

**Comment by torrin47** [comment]
Eh, I think we can call it done. It served its brief purpose and can stay in the completed column for later reference if needed.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#30
