### ISSUE TITLE
Elements: Title, Description, Last Update

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#67]
Title should be a plain text string input with at least 2 separate words, description should be a text area with at least 5 separate words, Last Update should be a ISO 8601 element with either a calendar selector or repeating interval selected from a dropdown.

**Comment by aergul** [comment]
EPA spec for "Last Update" indicates:
"Most recent date on which the dataset was changed, updated or modified, or for continually updated data, the frequency with which the data are updated."

This definition seems to overlap with "Update Frequency":
"The frequency with which dataset is published or updated."

How do we resolve this @torrin47 @jzichichi ?

**Comment by torrin47** [comment]
You're not wrong, it's a redundant feature of the Project Open Data Schema.
https://project-open-data.cio.gov/v1.1/schema/#modified
https://project-open-data.cio.gov/v1.1/schema/#accrualPeriodicity
I'm not sure there's much to resolve. From a practical perspective, modified should be a date and not a repeating interval unless the data refresh occurs more frequently than metadata catalogs can refresh.

**Comment by jzichichi** [comment]
@aergul 

Title looks good.  
Description looks like it shows valid with 3 separate words, as opposed to requirement "description should be a text area with at least 5 separate words"
Last Update looks good.

**Comment by aergul** [comment]
5 words enforced now for description

**Comment by jzichichi** [comment]
@aergul - Description looks good

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#22
