### ISSUE TITLE
Elements: Tags

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#68]
The final output of the tags element is a simple array of strings (duplicates not allowed) but the user interface needs to allow external users to select at least one tag from three different picklists: EPA Theme ISO Theme and Place (internal users will have 4!) as well as enter custom tags. The three external picklists are below. Internal tags will be a separate ticket. 

var epaKeywords = [
    'Agriculture',
    'Air',
    'Biology',
    'Boundaries and Base Data',
    'Chemicals',
    'Cleanup',
    'Climate',
    'Climate Change',
    'Compliance',
    'Conservation',
    'Contaminant',
    'Disaster',
    'Drinking Water',
    'Ecological',
    'Ecology',
    'Ecosystem',
    'Emergency',
    'Emergency Response',
    'Energy',
    'Enforcement',
    'Environment',
    'Environmental Justice',
    'Estuary',
    'Exposure',
    'Facilities',
    'Grants',
    'Ground Water',
    'Hazards',
    'Health',
    'Human',
    'Impact',
    'Indicator',
    'Indoor Air',
    'Inspections',
    'Land',
    'Management',
    'Marine',
    'Modeling',
    'Monitoring',
    'Natural Resources',
    'Permits',
    'Pesticides',
    'Quality',
    'Radiation',
    'Recreation',
    'Regulated Facilities',
    'Regulatory',
    'Remediation',
    'Response',
    'Risk',
    'Sites',
    'Spills',
    'Surface Water',
    'Sustainability',
    'Toxics',
    'Transportation',
    'Waste',
    'Water',
  ];
var placeKeywords = [
    'United States',
    'Canada',
    'Mexico',
    'Alaska',
    'Hawaii',
    'Washington DC',
    'American Samoa',
    'Puerto Rico',
    'Virgin Islands',
    'Alabama',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ];

var isoKeywords = [
'farming',
'biota',
'climatologyMeteorologyAtmosphere',
'economy',
'elevation',
'environment',
'geoscientificInformation',
'health',
'imageryBaseMapsEarthCover',
'intelligenceMilitary',
'inlandWaters',
'location',
'planningCadastre',
'society',
'structure',
'transportation',
'utilitiesCommunication'
];

**Comment by aergul** [comment]
@torrin47 I had started a similar js file for the purpose of configuring options for keywords, initially for ISO. Assuming we may want to display something friendlier, I built in key-value pairs to include both the keyword and its human friendly version. 

```
export default {
  iso_theme: {
    availableTags: [
      { key: "farming", value: "farming" },
      { key: "biota", value: "biota" },
      { key: "boundaries", value: "boundaries" },
      {
        key: "climatologyMeteorologyAtmosphere",
        value: "climatology / meteorology / atmosphere"
      },
      { key: "economy", value: "economy" },
      { key: "elevation", value: "elevation" },
      { key: "environment", value: "environment" },
      {
        key: "geoscientificInformation",
        value: "geoscientific information"
      },
      { key: "health", value: "health" },
      {
        key: "imageryBaseMapsEarthCover",
        value: "imagery / base maps / earth cover"
      },
      { key: "intelligenceMilitary", value: "intelligence / military" },
      { key: "inlandWaters", value: "inland waters" },
      { key: "location", value: "location" },
      { key: "oceans", value: "oceans" },
      { key: "planningCadastre", value: "planning / cadastre" },
      { key: "society", value: "society" },
      { key: "structure", value: "structure" },
      { key: "transportation", value: "transportation" },
      { key: "utilitiesCommunication", value: "utilities / communication" }
    ]
  }
};
```
We can switch to a keyword only config but wanted to see if its preferable to keep the friendly naming?

**Comment by torrin47** [comment]
Yes, I would absolutely agree that while the EPA and Place keywords are self-explanatory, I've often wondered about the intended definitions of those ISO categories, and often find myself referring back to this page for clarification: 
https://geo-ide.noaa.gov/wiki/index.php?title=ISO_Topic_Categories
Are these expanded definitions with examples worth baking into the tool, or just referencing via the help?

**Comment by jzichichi** [comment]
@torrin47 @aergul - is there a next step here?

**Comment by jzichichi** [comment]
@torrin47 - the expanded definitions with examples have been added into  the tool via additional 'i' icons for each ISO keyword, drawing from https://geo-ide.noaa.gov/wiki/index.php?title=ISO_Topic_Categories

I will move this item over to done.

**Comment by torrin47** [comment]
Swanky!

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#21
