### ISSUE TITLE
Elements: Publishing Organization, Publisher, Publisher Email

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#71]
The project open data schema allows a publisher element to be a nested object:
https://project-open-data.cio.gov/v1.1/schema/#publisher
we've never offered that option to EPA audiences, and they've never requested it, so I'm inclined to make this element a plain text string in the MVP, and postpone further flexibility as an optional enhancement down the road. 

Publisher should be a plain text element with minimal validation - it must have some value, but any value is acceptable.
Publisher email must validate with email address syntax.

If and when we implement ORCID authentication, all of these elements should be pulled from the ORCID API - though we'll want to explore the implications of that option. Presumably we'll need to allow the user to select from multiple possible organizations and name and email variants as well as edit the values after they're populated.

**Comment by jzichichi** [comment]
@aergul 
According to requirement above, "Publisher should be a plain text element with minimal validation - it must have some value, but any value is acceptable."  It looks like current validation requires more than just "any value", since it doesn't like just "Jessica"  

Publishing Organization seems to have the same rules but I don't see anything specific for that element listed above.  @torrin47  - for publishing organization, should this be a defined list or is it free text well?

email looks OK

**Comment by torrin47** [comment]
For internal users (when we eventually focus on them) we'll want a picklist from the EPA org chart, but for the MVP for external users we'll need it to be free text. An enhancement will be to allow it to be populated from an external user's ORCID data - though I think it'd make more sense to wire this up to an EPA grants database, since in theory every external user has received an EPA grant. Apparently that's not under consideration.

**Comment by jzichichi** [comment]
OK, thanks @torrin47.  @aergul, see comments above for publisher and publishing organization.
And this:

![Untitled.png](https://images.zenhubusercontent.com/5b889669f9c188212a6dc1cd/0cbfcfa3-d695-4d90-a63d-0637773cee67)

**Comment by aergul** [comment]
Publisher is supposed to be the full name of a person. Will we really accept "Jessica"?

**Comment by torrin47** [comment]
I'm having a hard time coming up with an example of a one-word publisher, but my inclination is to be lenient, because despite the official POD guidance EPA and other agencies allow Publisher and Publisher Email to point at a helpdesk instead of an individual, on the reasoning that a team can be more responsive and provide more continuity.

**Comment by aergul** [comment]
One word it is...

**Comment by jzichichi** [comment]
@aergul these look good to me.

**Comment by torrin47** [comment]
I don't think we should ask the end user to populate the mailto: prefix on the email address, I think we should take care of that for them under the hood.

**Comment by aergul** [comment]
We now handle the mailto: part for the user.

**Comment by jzichichi** [comment]
@aergul - looks good to me. I will move this over, but @torrin47 feel free to weigh in if you like

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#18
