### ISSUE TITLE
Elements: Identifier

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#72]
If a user doesn't have an existing identifier such as a DOI, they should be able to click a button to generate a new UUID for this element. From a UX perspective, it's probably best to automatically generate the UUID by default, so a user only has to take an action if they have their own ID, otherwise they can sail past this element.

**Comment by jzichichi** [comment]
@aergul I like it - maybe we should see how @torrin47 likes the identifier implementation at https://podme-dev.coronaenv.com/

**Comment by torrin47** [comment]
Yeah, very slick, I like it too.  Will see whether the EPA folks want to wordsmith, but functionally it's great.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#17
