### ISSUE TITLE
Elements: Access Level, Rights, and License

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#73]
Access level has only three valid values: "public", "restricted public", "non-public".

If access level is public, Rights is optional and free text. If access level is not public, Rights is mandatory and must be selected from the following list:

- EPA Category: Mission Sensitive, NARA Category: Critical Infrastructure
- EPA Category: Drinking Water Vulnerability Assessments, NARA Category: Critical Infrastructure-Water Assessments
- EPA Category: Sensitive Drinking Water Related, NARA Category: Critical Infrastructure-Water Assessments
- EPA Category: IT Security, NARA Category: Information Systems Vulnerability Information
- EPA Category: Law Enforcement Sensitive, NARA Category: Law Enforcement
- EPA Category: Attorney Client Privilege, NARA Category: Legal-Privilege
- EPA Category: Attorney Work Product, NARA Category: Legal-Privilege
- EPA Category: Deliberative Process Privilege, NARA Category: Legal-Privilege
- EPA Category: Personally Identifiable Information (PII), NARA Category: Privacy
- EPA Category: Proprietary, NARA Category: Proprietary
- EPA Category: Confidential Business Information, NARA Category: Proprietary-Manufacturer
- EPA Category: Source Selection Information, NARA Category: Proprietary-Source Selection

License must be a URL. We could potentially offer a picklist from the choices here: https://project-open-data.cio.gov/open-licenses/ but would definitely need to allow a user to specify their own license.

**Comment by aergul** [comment]
This is now implemented.

No picklist for license as I'm not sure if we are going for it. Is there non-trivial adoption of those licenses among extramural researchers? Or desire to encourage adoption?

**Comment by jzichichi** [comment]
@aergul - the implementation for access level and rights looks good; I will wait to hear back from @torrin47 regarding the license picklist question before moving it over.

**Comment by torrin47** [comment]
I'm ok with no picklist, provided we include links to the strongly recommended examples page in the guidance. But... it suddenly occurs to me that the guidance for this element in particular (and probably a few others) will be different for EPA users, who we definitely want to default to the standard EPA license.  This suggests that maybe our help schema needs to be expanded to allow optional elements with "epaonly" guidance or "externalonly" guidance?

**Comment by jzichichi** [comment]
@torrin47 updating guidance to include new categories as described above.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#15

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#16
