### ISSUE TITLE
Elements: Temporal Extent, Update Frequency, Release Date

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#74]
All of these elements are optional and should validate as ISO 8601 Dates or ranges. Maybe they could be grouped?

**Comment by jzichichi** [comment]
@torrin47 - @aergul and I were wondering which element "Release Date" maps to in the POD schema?

**Comment by torrin47** [comment]
Not sure how to explain why the element name is so different from the Label - the element name is "issued":

https://project-open-data.cio.gov/v1.1/schema/#issued

**Comment by aergul** [comment]
Does "issued" or equivalent appear in EPA schema?

**Comment by torrin47** [comment]
Ahh, yes, so the technical specification was intended to be limited to those elements that were:

1. Mandatory in POD or
2. Mandatory in ISO or
3. Where EPA had some additional guidance or requirement above and beyond the base guidance for those schemas.

issued is one of those elements that are optional and we had nothing to add to the POD guidance. There are only a few others that fall into this category, but we do need to include them in this tool - I'm pretty sure I captured them all in GitHub issues.  And that means we also need to include them in our guidance JSON - using the guidance from the Project Open Data site.

**Comment by aergul** [comment]
I'm putting this out there without a separate field for update frequency for now.
It doesn't make sense to have two separate widgets to enter the periodicity of the data set. 
I'm inclined to have "Last Update" be a date entry only and "Update Frequency" to be the vehicle for entering periodicity (as @torrin47 suggested in #67 ) and handle json element generation behind the scenes but it has implications for validation and guidance that we might want to talk about before doing so.

**Comment by jzichichi** [comment]
@aergul - perhaps we can discuss this Monday at our check-in. I agree it seems confusing to have the user enter periodicity twice.

**Comment by torrin47** [comment]
Going to let user optionally leave last update blank and use periodicity to set repeating interval. if both are blank, both are invalid.

**Comment by aergul** [comment]
Changes implemented

**Comment by jzichichi** [comment]
@aergul - appears to work as described above. Moving to EPA column for @torrin47 to review

**Comment by torrin47** [comment]
👍

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#13

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#14
