### ISSUE TITLE
Elements: Conforms To, Described By (+type), Landing Page, References

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#77]
All of these elements are optional, and all should validate as URLs - though described by type is a mime type with the associated complications, and references is an unordered array of URLs (that I really wish we could include title/description/type information along with).

**Comment by aergul** [comment]
These are implemented except describedByType. There are many ways to tackle that element ranging from simplistic to onerous to ridiculous - given the variety of mime types available. I am attaching a list here if anyone wants to boil it down to a reasonable list or suggest an alternative approach. 

[extension_mimetype.csv](https://app.zenhub.com/files/98460260/d1d6c8d2-dc54-4b23-a284-81067e017c25/download)

**Comment by jzichichi** [comment]
@aergul, wow that is indeed an amazing list of mime types. I am not sure if @torrin47 may have a suggestion for a smaller subset - given experience with records posted to EDG and typical mime types that groups tend to document?  The implementation of the other fields looks good; I noticed we have no guidance for those.  Do we want to add guidance to the current json file?  I don't think those are listed specifically in the spec, but I may have overlooked them somewhere.

**Comment by torrin47** [comment]
In the spreadsheet we've been using as our non-geo metadata editor for years we've provided the following shortlist of MIME types:
  
text/plain
text/csv
text/html
application/xml
application/zip

Nobody has ever asked for more, but it's an optional element and I'm guessing they just skip it.  The full list is definitely long and full of obscure types, but I'm not sure it's longer or more obscure than the language list and a similar approach would be fine.

**Comment by jzichichi** [comment]
@torrin47 - we will use the mechanism we've used for language with full list of MIME types; will float the following to the top as well: 
text/plain
text/csv
text/html
application/xml
application/zip

Assigning back over to @aergul

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#10
