### ISSUE TITLE
Update Look/Feel of PODME interface 

### ISSUE THREAD

**Issue by jzichichi** [USEPA/EPA_Environmental_Dataset_Gateway#81]
Basic enhancements for visual appeal:
1. PODME Title appears too large for space provided; make smaller
2. Font should be made consistent across the board (size and style). 

@torrin47 - do you have a preference for font sizes and styles? Also, please add any other visual feedback you'd like.

**Comment by torrin47** [comment]
No strong feelings, my inclination is to stick close to the CSS on EPA's main site unless there's a good reason to deviate.
https://www.epa.gov/webguide

**Comment by jzichichi** [comment]
@torrin47 - great thank you.  Is there a good reason why it's blocking me from accessing it?

![Untitled.png](https://images.zenhubusercontent.com/5b889669f9c188212a6dc1cd/f61f85ac-3a41-41e8-ad45-05d3ed5b458e)

**Comment by torrin47** [comment]
Wow, that strikes me as a bug, I can't imagine why they'd deliberately block it.  Web standards is accessible, but not the guide or styleguide:
https://www.epa.gov/web-policies-and-procedures/epa-web-standards
https://www.epa.gov/webguide/web-style-guide
Submitting a ticket for more info.

**Comment by aergul** [comment]
It is annoying that some of those useful links greet you with "access denied" without indication of them being intranet pages.

Meanwhile, now that we have validation icons, do we want to get rid of the (i)nfo icons? The two have the same utility and I don't think assigning separate functions to them would improve user experience.  Thoughts?

**Comment by torrin47** [comment]
Here's a link to the white EPA Logo in png.  https://epa.maps.arcgis.com/home/item.html?id=339f10f5a3154fa1a8eff8efa5957eb1

**Comment by aergul** [comment]
Pushed the latest although there are some minor details still in progress.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#6
