### ISSUE TITLE
Introductory Paragraph on the page

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Environmental_Dataset_Gateway#85]
Draft some initial guidance to appear at the top of the page.

**Comment by torrin47** [comment]
Welcome to the EPA Open Data Metadata Editor in support of EPA's initiative to make data open, discoverable, and usable. This tool allows data owners to author, save, and submit metadata records that are compliant with [EPA's Metadata Technical Specification](https://www.epa.gov/geospatial/epa-metadata-technical-specification). Each element has a corresponding status: Mandatory (empty), Optional (empty), Invalid, and Valid. Additional guidance and best practices are available by clicking each element's status icon. Use the menu at the lower right to save, load, or submit records or log in as an EPA user. Please contact the [EPA EDG team](mailto:edg@epa.gov) with any questions.

Good enough?
@aergul @jzichichi

**Comment by aergul** [comment]
Added the intro, with some starter styling. Open to changes (including the bg picture).

**Comment by torrin47** [comment]
🥇 👍 👍 👍

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#2
