### ISSUE TITLE
Update Guidance Document to include missing elements

### ISSUE THREAD

**Issue by jzichichi** [USEPA/EPA_Environmental_Dataset_Gateway#86]
Currently, guidance is missing for the following fields:
Release Date
Data Quality
Conforms To
Described By
Landing Page
References

@torrin47, I can make an attempt at guidance for the JSON file based on the POD schema, or I am not sure if you prefer that the official tech spec be updated first and provide the authoritative source of content for the PODME interface.

**Comment by torrin47** [comment]
I don't mind doing this, but I don't expect to include these items in the tech spec - when we flip this around and write some code to populate the tech spec page using this JSON, I would have the code skip over these elements, or at least draw a clear distinction between them and the rest.

**Comment by jzichichi** [comment]
Latest file from Ayhan; attaching here to reference for adding new elements listed above.  JZ to add elements in a first pass today.

[https://app.zenhub.com/files/98460260/c79ca45e-cb57-4647-8d49-ac60bd0143f9/download](https://app.zenhub.com/files/98460260/c79ca45e-cb57-4647-8d49-ac60bd0143f9/download)

**Comment by jzichichi** [comment]
@aergul - here's the latest.  I hope I didn't leave any stragglers.

[https://app.zenhub.com/files/98460260/f9d65589-51f4-42f0-ad05-6a4d658ff583/download](https://app.zenhub.com/files/98460260/f9d65589-51f4-42f0-ad05-6a4d658ff583/download)

**Comment by aergul** [comment]
updated with some pruning
[epa-metadata-tech-spec.txt](https://app.zenhub.com/files/98460260/6ccdd893-6323-4059-89ae-b0cf0e8c9d6e/download)

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#1
